### ISSUE TITLE
The loading screen doesn't cover whole page

### ISSUE THREAD

**Issue by ez-sherlock** [eknoorpreet/dev.to-clone#1]
If you scroll while on the loading screen you can see some posts behind it. The loading screen doesn't cover the whole page.
![image](https://user-images.githubusercontent.com/89704304/161416470-9761a92b-d3c5-473a-a6d6-1a85b26f8235.png)

**Comment by ez-sherlock** [comment]
Please assign this to me. I can fix that. Thanks :)

**Comment by eknoorpreet** [comment]
Hey @ez-sherlock, the loading screen was a temporary feature. I had planned to replace it with skeleton loading and have already implemented it in the project in my recent commits. I'll be closing the issue. Regardless, thank you for contributing :)
